# Generated by Django 4.1.1 on 2023-05-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokrytia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokrytie', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Покрытие')),
            ],
            options={
                'verbose_name': 'Покрытие',
                'verbose_name_plural': 'Покрытия',
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Номер')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Наименование')),
                ('owner', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Собственник')),
                ('znachenie', models.CharField(blank=True, choices=[('fed', 'федеральная'), ('reg', 'региональная'), ('mest', 'местная'), ('chas', 'частная'), ('ved', 'ведомственная')], default=None, max_length=255, null=True, verbose_name='Принадлежность')),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
            },
        ),
        migrations.CreateModel(
            name='Uchastki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnumber', models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер подучастка')),
                ('category', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Категория')),
                ('osevaya_nagruzka', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Осевая нагрузка')),
                ('start_uchastka', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Категория')),
                ('end_uchastka', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Категория')),
                ('full_lenght', models.FloatField(blank=True, default=None, null=True, verbose_name='Протяженность вида покрытия')),
                ('etap_proekta', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Категория')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.roads', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
            },
        ),
        migrations.CreateModel(
            name='PokrytiaUchastkov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protyazhennost', models.FloatField(blank=True, default=None, null=True, verbose_name='Протяженность вида покрытия')),
                ('uchastok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.uchastki', verbose_name='Участок')),
                ('vid_pokrytia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.pokrytia', verbose_name='Вид покрытия')),
            ],
            options={
                'verbose_name': 'Покрытие на участке',
                'verbose_name_plural': 'Покрытия на участках',
            },
        ),
    ]
