# Generated by Django 4.1.1 on 2023-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchastki',
            name='km',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Километры'),
        ),
        migrations.AlterField(
            model_name='uchastki',
            name='end_uchastka',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='uchastki',
            name='etap_proekta',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='uchastki',
            name='full_lenght',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='uchastki',
            name='start_uchastka',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='от'),
        ),
    ]
