# Generated by Django 4.1.1 on 2023-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_uchastki_km_alter_uchastki_end_uchastka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uchastki',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
    ]
