# Generated by Django 4.1.1 on 2023-05-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_alter_uchastki_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokrytia',
            new_name='Pokrytie',
        ),
        migrations.RenameModel(
            old_name='PokrytiaUchastkov',
            new_name='PokrytieUchastka',
        ),
        migrations.RenameModel(
            old_name='Roads',
            new_name='Road',
        ),
        migrations.RenameModel(
            old_name='Uchastki',
            new_name='Uchastok',
        ),
    ]
