# Generated by Django 4.2.2 on 2023-06-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_pokrytie_sokr_pokrytie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Название объекта')),
                ('dogovor_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Znachenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znachenie', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AlterField(
            model_name='pokrytie',
            name='sokr_pokrytie',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Сокращенное написание'),
        ),
        migrations.AddField(
            model_name='road',
            name='objects_r',
            field=models.ManyToManyField(related_name='objects_names', to='roads.nameobject', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='road',
            name='znachenie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='roads.znachenie', verbose_name='Значение'),
        ),
    ]
