# Generated by Django 4.2.2 on 2023-06-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0006_nameobject_znachenie_alter_pokrytie_sokr_pokrytie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='objects_r',
            field=models.ManyToManyField(blank=True, default=None, related_name='objects_names', to='roads.nameobject', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='road',
            name='znachenie',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='roads.znachenie', verbose_name='Значение'),
        ),
    ]
