# Generated by Django 4.2.2 on 2023-06-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0009_alter_road_znachenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='objects_r',
            field=models.ManyToManyField(default=None, null=True, related_name='objects_names', to='roads.nameobject', verbose_name='Объекты'),
        ),
    ]
