# Generated by Django 4.2.2 on 2023-06-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0010_alter_road_objects_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='znachenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roads.znachenie', verbose_name='Значение'),
        ),
    ]
