# Generated by Django 4.2.2 on 2023-06-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0012_nameobject_in_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectEtap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etap_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Номер договора')),
                ('etap_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Номер договора')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.nameobject', verbose_name='Этапы"')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
