# Generated by Django 4.1.1 on 2023-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0013_objectetap'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameobject',
            name='short_object_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='objectetap',
            name='etap_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='objectetap',
            name='etap_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Номер этапа'),
        ),
    ]
