# Generated by Django 4.2.2 on 2023-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0014_nameobject_object_short_name_and_more'),
        ('roads', '0014_nameobject_short_object_name_and_more'),
    ]

    operations = [
    ]
