# Generated by Django 4.1.1 on 2023-07-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0015_merge_20230701_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameobject',
            name='object_short_name',
        ),
        migrations.RemoveField(
            model_name='road',
            name='objects_r',
        ),
        migrations.AddField(
            model_name='uchastok',
            name='objects_r',
            field=models.ManyToManyField(default=None, null=True, related_name='objects_names', to='roads.nameobject', verbose_name='Объекты'),
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='etap_proekta',
        ),
        migrations.AddField(
            model_name='uchastok',
            name='etap_proekta',
            field=models.ManyToManyField(default=None, null=True, related_name='etap_names', to='roads.objectetap', verbose_name='Этапы'),
        ),
    ]
