# Generated by Django 4.1.1 on 2023-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0016_remove_nameobject_object_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uchastok',
            name='objects_r',
        ),
        migrations.AddField(
            model_name='road',
            name='objects_r',
            field=models.ManyToManyField(default=None, null=True, related_name='objects_names', to='roads.nameobject', verbose_name='Объекты'),
        ),
    ]
