# Generated by Django 4.2.1 on 2023-05-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorogi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Briges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepyat', models.CharField(max_length=255)),
                ('km', models.CharField(max_length=255)),
                ('god_postr', models.IntegerField()),
                ('proekt_nagr', models.CharField(max_length=255)),
                ('pol_shir', models.FloatField()),
                ('gabarit', models.FloatField()),
                ('trotuar', models.FloatField()),
                ('tol_dor_od', models.FloatField()),
                ('stat_sist', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('tip_proekt', models.CharField(max_length=255, null=True)),
                ('prod_schema', models.CharField(max_length=255)),
                ('poln_dlina', models.FloatField()),
                ('chis_bal', models.CharField(max_length=255)),
                ('poper_schema', models.CharField(max_length=255)),
                ('param_bal', models.CharField(max_length=255)),
                ('doroga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='briges.dorogi')),
            ],
        ),
    ]
