# Generated by Django 4.1.1 on 2023-05-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('briges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briges',
            options={'verbose_name': 'Мосты', 'verbose_name_plural': 'Мосты'},
        ),
        migrations.AlterModelOptions(
            name='dorogi',
            options={'verbose_name': 'Дороги', 'verbose_name_plural': 'Дороги'},
        ),
        migrations.AlterField(
            model_name='briges',
            name='chis_bal',
            field=models.CharField(max_length=255, verbose_name='Число балок'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='doroga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='briges.dorogi', verbose_name='Автодорога'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='gabarit',
            field=models.FloatField(verbose_name='Габарит'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='god_postr',
            field=models.IntegerField(default=None, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='km',
            field=models.CharField(max_length=255, verbose_name='Км'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='material',
            field=models.CharField(max_length=255, verbose_name='Статическая система'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='param_bal',
            field=models.CharField(max_length=255, verbose_name='Параметры балки'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='pol_shir',
            field=models.FloatField(verbose_name='Полная ширина'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='poln_dlina',
            field=models.FloatField(verbose_name='Полная длина'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='poper_schema',
            field=models.CharField(max_length=255, verbose_name='Поперечная схема'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='prepyat',
            field=models.CharField(max_length=255, verbose_name='Препятствие'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='prod_schema',
            field=models.CharField(max_length=255, verbose_name='Продольная схема'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='proekt_nagr',
            field=models.CharField(max_length=255, verbose_name='Проектные нагрузки'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='stat_sist',
            field=models.CharField(max_length=255, verbose_name='Статическая система'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='tip_proekt',
            field=models.CharField(max_length=255, null=True, verbose_name='Типовой проект (необязательно)'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='tol_dor_od',
            field=models.FloatField(verbose_name='Толщина дорожной одежды'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='trotuar',
            field=models.FloatField(verbose_name='Ширина тротуара'),
        ),
    ]
