# Generated by Django 4.1.1 on 2023-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briges', '0002_alter_briges_options_alter_dorogi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briges',
            name='chis_bal',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Число балок'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='gabarit',
            field=models.FloatField(default=None, null=True, verbose_name='Габарит'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='km',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Км'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='material',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Статическая система'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='param_bal',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Параметры балки'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='pol_shir',
            field=models.FloatField(default=None, null=True, verbose_name='Полная ширина'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='poln_dlina',
            field=models.FloatField(default=None, null=True, verbose_name='Полная длина'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='poper_schema',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Поперечная схема'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='prepyat',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Препятствие'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='prod_schema',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Продольная схема'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='proekt_nagr',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Проектные нагрузки'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='stat_sist',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Статическая система'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='tip_proekt',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Типовой проект (необязательно)'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='tol_dor_od',
            field=models.FloatField(default=None, null=True, verbose_name='Толщина дорожной одежды'),
        ),
        migrations.AlterField(
            model_name='briges',
            name='trotuar',
            field=models.FloatField(default=None, null=True, verbose_name='Ширина тротуара'),
        ),
    ]
