# Generated by Django 4.1.1 on 2023-05-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_rename_pokrytia_pokrytie_and_more'),
        ('briges', '0004_alter_briges_chis_bal_alter_briges_gabarit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briges',
            name='doroga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.road', verbose_name='Автодорога'),
        ),
    ]
